#!/usr/bin/env bash
# submit.sh
# Usage: ./submit.sh <partition_alias> <sbatch_script>

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <partition_alias> <sbatch_script>"
    echo "Aliases: cpu, gpu, top, or exact queue name"
    exit 1
fi

QUEUE_ALIAS="$1"
SBATCH_PATH="$2"

case "$QUEUE_ALIAS" in
    cpu) PARTITION="armq,defq,fpgaq,genoaxq,gh200q,h200q,habanaq,huaq,milanq,rome16q,xeonmaxq" ;;
    gpu) PARTITION="dgx2q,a40q,a100q,hgx2q,gh200q" ;;
    top) PARTITION="genoaxq,h200q,gh200q" ;;
    *) PARTITION="$QUEUE_ALIAS" ;;
esac

set -x
SBATCH_NAME=$(basename "$SBATCH_PATH" ".sbatch")
RUN_DIR="$HOME/runs/${SBATCH_NAME}"
LOG_DIR="logs/${SBATCH_NAME}"
RESULT_DIR="results/${SBATCH_NAME}"
mkdir -p "$RUN_DIR" "$LOG_DIR" "$RESULT_DIR"
git ls-files -z | rsync -a -0 --exclude="logs/" --exclude="results/" --files-from=- ./ "$RUN_DIR/"
rsync -a --exclude ".git/" --exclude "build/" --exclude "logs/" --exclude "results/" ./ "$RUN_DIR/"
ln -sf $(realpath "$LOG_DIR") "${RUN_DIR}/logs"
ln -sf $(realpath "$RESULT_DIR") "${RUN_DIR}/results"

cd "$RUN_DIR"
IFS=',' read -ra PARTS <<< "$PARTITION"
for P in "${PARTS[@]}"; do
    sbatch --partition="$P" --output "${LOG_DIR}/$P.out" --error "${LOG_DIR}/${P}.err" "$SBATCH_PATH"
done
